package com.ai.client;

import com.ai.config.AiTriageConfig;
import com.ai.model.AiTriageSummary;
import com.ai.model.ApiInteraction;
import com.ai.model.FailureEvidence;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.models.responses.Response;
import com.openai.models.responses.ResponseCreateParams;

import java.time.Duration;
import java.util.stream.Collectors;

/**
 * Calls the OpenAI Responses API with redacted failed-test evidence and returns
 * a structured defect-style triage summary.
 */
public class OpenAiTriageClient {
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    private static final String INSTRUCTIONS = """
            You are an API test failure triage expert for a Java REST Assured, JUnit 5, Maven automation framework.
            Analyze only the supplied redacted evidence and return valid JSON only.
            Do not invent API behavior, request fields, response fields, or business rules.
            Distinguish assertion failures, schema validation failures, API behavior changes, data issues, authentication issues, environment/network issues, and script issues.
            Return exactly one JSON object with these fields in this order: defectTitle, category, expectedResult, actualResult, suspectedRootCause, reproductionSteps, recommendedNextAction, confidenceScore.
            reproductionSteps must be an array of strings.
            confidenceScore must be an integer from 0 to 100.
            Do not wrap the JSON in markdown fences.
            """;

    /**
     * Sends the failed-test evidence to the configured OpenAI model.
     *
     * @param evidence redacted failure evidence collected by the test framework
     * @param apiKey OpenAI API key read from the ignored local properties file
     * @return structured triage summary generated by the model
     */
    public AiTriageSummary generateTriage(FailureEvidence evidence, String apiKey) {
        // Instantiate a new client for each request.
        OpenAIClient client = OpenAIOkHttpClient.builder()
                .apiKey(apiKey)
                .timeout(Duration.ofSeconds(AiTriageConfig.timeoutSeconds()))
                .maxRetries(AiTriageConfig.maxRetries())
                .build();

        // Set up the model request with instructions, evidence-based prompt, and output configuration.
        ResponseCreateParams params = ResponseCreateParams.builder()
                .model(AiTriageConfig.model())
                .instructions(INSTRUCTIONS)
                .input(promptFor(evidence))
                .maxOutputTokens(AiTriageConfig.maxOutputTokens())
                .store(false)
                .build();

        // Send the request and parse the structured JSON from the model's response.
        Response response = client.responses().create(params);
        return parseSummary(extractRawJson(response));
    }

    /**
     * Extracts JSON raw text from the model response
     *
     * @param response OpenAI Responses API response
     * @return joined output text from all message content blocks
     */
    private static String extractRawJson(Response response) {
        return response.output().stream()
                .flatMap(item -> item.message().stream())
                .flatMap(message -> message.content().stream())
                .flatMap(content -> content.outputText().stream())
                .map(outputText -> outputText.text())
                .collect(Collectors.joining(System.lineSeparator()))
                .trim();
    }

    /**
     * Parses and validates model JSON into the framework's structured triage summary.
     *
     * @param rawJson raw JSON text returned by the model
     * @return validated structured triage summary
     */
    private static AiTriageSummary parseSummary(String rawJson) {
        if (rawJson == null || rawJson.isBlank()) {
            throw new IllegalArgumentException("OpenAI returned an empty triage response.");
        }

        try {
            return OBJECT_MAPPER.readValue(jsonObject(rawJson), AiTriageSummary.class);
        } catch (JsonProcessingException exception) {
            throw new IllegalArgumentException("OpenAI returned invalid triage JSON.", exception);
        }
    }

    /**
     * Extracts the JSON object from model output in case the response includes surrounding text.
     *
     * @param value raw model output
     * @return substring containing the JSON object
     */
    private static String jsonObject(String value) {
        int start = value.indexOf('{');
        int end = value.lastIndexOf('}');

        if (start < 0 || end <= start) {
            throw new IllegalArgumentException("OpenAI triage response does not contain a JSON object.");
        }

        // The model should ideally return only JSON, but this ensures we can still parse valid JSON even if the model includes extra text.
        return value.substring(start, end + 1);
    }

    /**
     * Builds the prompt input from failed-test metadata, stack trace excerpt, and HTTP evidence.
     *
     * @param evidence redacted evidence package for one failed test
     * @return prompt text sent to the model
     */
    private static String promptFor(FailureEvidence evidence) {
        StringBuilder builder = new StringBuilder();
        appendFailureMetadata(builder, evidence);
        appendStackTrace(builder, evidence);
        appendHttpInteractions(builder, evidence);
        return builder.toString();
    }

    /**
     * Adds high-level failed-test metadata to the model prompt.
     *
     * @param builder prompt builder being assembled
     * @param evidence redacted evidence package for one failed test
     */
    private static void appendFailureMetadata(StringBuilder builder, FailureEvidence evidence) {
        builder.append("""
                # Failed Test Evidence

                - Test class: %s
                - Test display name: %s
                - API domain: %s
                - Duration: %d ms
                - Failure type: %s
                - Failure message: %s

                """.formatted(
                evidence.testClassName(),
                evidence.testDisplayName(),
                evidence.apiDomain(),
                evidence.durationMs(),
                evidence.failureType(),
                evidence.failureMessage()
        ));
    }

    /**
     * Adds the bounded stack trace excerpt to the model prompt.
     *
     * @param builder prompt builder being assembled
     * @param evidence redacted evidence package for one failed test
     */
    private static void appendStackTrace(StringBuilder builder, FailureEvidence evidence) {
        builder.append("""
                ## Stack Trace Excerpt
                ```text
                %s
                ```
                """.formatted(limit(evidence.stackTraceExcerpt(), 5000)));
    }

    /**
     * Adds all captured HTTP interactions to the model prompt.
     *
     * @param builder prompt builder being assembled
     * @param evidence redacted evidence package for one failed test
     */
    private static void appendHttpInteractions(StringBuilder builder, FailureEvidence evidence) {
        if (evidence.interactions().isEmpty()) {
            builder.append("""

                    ## HTTP Interactions
                    No REST Assured HTTP interactions were captured before the failure.
                    """);
            return;
        }

        builder.append(System.lineSeparator()).append("## HTTP Interactions").append(System.lineSeparator());
        for (int index = 0; index < evidence.interactions().size(); index++) {
            appendHttpInteraction(builder, index + 1, evidence.interactions().get(index));
        }
    }

    /**
     * Adds one captured HTTP interaction to the model prompt.
     *
     * @param builder prompt builder being assembled
     * @param interactionNumber human-readable interaction number
     * @param interaction redacted HTTP request and response evidence
     */
    private static void appendHttpInteraction(StringBuilder builder, int interactionNumber, ApiInteraction interaction) {
        builder.append("""

                ### Interaction %d
                - Method: %s
                - URI: %s
                - Response status: %d
                - Response time: %d ms

                #### Request
                ```text
                %s
                ```

                #### Response
                ```text
                %s
                ```
                """.formatted(
                interactionNumber,
                interaction.method(),
                interaction.uri(),
                interaction.responseStatus(),
                interaction.responseTimeMs(),
                limit(interaction.requestAttachment(), 6000),
                limit(interaction.responseAttachment(), 6000)
        ));
    }

    /**
     * Truncates large evidence fields so the model request remains bounded and readable.
     *
     * @param value text to include in the prompt
     * @param maxLength maximum number of characters to keep
     * @return original text, a placeholder, or a truncated excerpt
     */
    private static String limit(String value, int maxLength) {
        if (value == null || value.isBlank()) {
            return "(none)";
        }
        if (value.length() <= maxLength) {
            return value;
        }
        return value.substring(0, maxLength) + System.lineSeparator() + "... [truncated]";
    }
}
